name: Docker Publish

on:
  push:
    # 当 master 或 main 分支有推送时触发
    branches:
      - master
      - main
    # 当一个 v* 格式的 tag 被推送时触发 (e.g. v1.2.3)
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 需要写权限来推送到 GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # 确保拉取 submodules

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # 使用你的仓库名作为镜像名

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # 构建支持 x86 和 arm 的多架构镜像
          push: true # 确认推送
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
